version: '3.4'

services:
    redis1:
        image: redis
        ports:
            - "6379:6379"
    
    hello-node-js:
        image: sunny5/hello-node-js
        expose:
            - "85"
        ports: 
            - "85:80"
        depends_on: 
            - redis1
        
        